version: '2.4'
services:
    app: 
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/springboot:latest
        volumes: 
            - ./app/:/data/app/
            - ./config/application.yml:/data/config/application.yml:ro
        environment:
            JAVA_OPTS: -server -Xms128m -Xmx1g -Djava.security.egd=file:/dev/./urandom
        ports: 
            - "8080:8080"
        entrypoint:
            - /entrypoint.sh
            - --spring.config.location=/data/config/application.yml
        restart: on-failure
        logging:
            driver: 'json-file'
            options:
                max-size: '12m'
                max-file: '5'
