version: '2'
services:
    app:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/frp
        network_mode: "host"
        volumes:
            - ./frpc.ini:/data/frp/frpc.ini:z
        restart: always
        entrypoint:
            - ./frp/frpc
            - -c
            - /data/frp/frpc.ini

