version: '2'
services:
    web:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/nginx:alpine-1.11.9
        container_name: "nginx"
        ports:
            - "80:80"
        volumes:
            - ./data/html/:/usr/share/nginx/html
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/conf.d/:/etc/nginx/conf.d/
        restart: on-failure
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '20'

