version: '2.4'
services:
    webUI:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/registry-frontend:v2
        container_name: 'docker-registry-webUI'
        ports:
            - 8080:80
        restart: on-failure
        environment:
            - "ENV_DOCKER_REGISTRY_HOST=registry"
            - "ENV_DOCKER_REGISTRY_PORT=443"
            - "ENV_DOCKER_REGISTRY_USE_SSL=1"
            - "ENV_MODE_BROWSE_ONLY=true"
            - "ENV_DEFAULT_REPOSITORIES_PER_PAGE=20"
        depends_on:
            - registry
        logging:
            driver: 'json-file'
            options:
                max-size: '12m'
                max-file: '5'
    registry:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/registry:2
        container_name: 'docker-registry'
        ports:
            - 443:443
        volumes:
            - ./data/registry:/var/lib/registry
            - ./certs:/certs:ro
        restart: on-failure
        environment:
            - REGISTRY_HTTP_ADDR=0.0.0.0:443
            - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt
            - REGISTRY_HTTP_TLS_KEY=/certs/registry.key
        logging:
            driver: 'json-file'
            options:
                max-size: '12m'
                max-file: '5'

