version: '2'
    
networks:
    &network wlsnet:
        driver: bridge

services:
    &admin adminserver:
        image: &image registry.cn-hangzhou.aliyuncs.com/kennylee/weblogic-domain:12.2.1.2.0-jre8
        container_name: wlsadmin
        volumes:
            - './app/:/u01/oracle/app/'
            - './container-scripts/:/u01/oracle/my-scripts/'
            - './libs/:/u01/oracle/user_projects/domains/base_domain/lib/'
        ports:
            - "8001:8001"
        networks:
            - *network 
        env_file:
            - admin.env
    server1:
        image: *image
        command: createServer.sh
        volumes:
            - './app/:/u01/oracle/app/'
            - './libs/:/u01/oracle/user_projects/domains/base_domain/lib/'
        ports:
            - "7001:7001"
        networks:
            - *network 
        env_file:
            - app.env
        depends_on:
            - *admin
    server2:
        image: *image
        command: createServer.sh
        volumes:
            - './app/:/u01/oracle/app/'
            - './libs/:/u01/oracle/user_projects/domains/base_domain/lib/'
        ports:
            - "7002:7001"
        networks:
            - *network
        env_file:
            - app.env
        depends_on:
            - *admin
