version: '2.4'
services:
    runner:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/gitlab-ci-multi-runner
        container_name: gitlab-runner
        volumes:
            - ./data:/home/gitlab_ci_multi_runner/data:z
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - TZ=Asia/Shanghai
            - CI_SERVER_URL=${CI_SERVER_URL}
            - RUNNER_TOKEN=${RUNNER_TOKEN}
            - RUNNER_DESCRIPTION=${RUNNER_DESCRIPTION}
            - RUNNER_EXECUTOR=shell
        extra_hosts:
            - "gitlab.foo.com:192.168.3.231"
        restart: on-failure
        logging:
            driver: 'json-file'
            options:
                max-size: '12m'
                max-file: '5'
