version: '2'
services:
    app:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/gollum
        container_name: gollum
        ports:
            - "4567:80"
        volumes:
            - ./data:/wiki:z
        restart: on-failure
        logging:
            driver: 'json-file'
            options:
                max-size: '12m'
                max-file: '5'



