version: '2'
services:
    app:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/opencv:tomcat8
        ports:
            - "8080:8080"
        volumes:
            - ./app/webapps/:/opt/tomcat/webapps/:z
            - ./config/server.xml:/opt/tomcat/conf/server.xml:ro
            - ./data/logs/:/opt/tomcat/logs/:z
        environment:
            - JAVA_OPTS=-server -Xms128m -Xmx1g -Djava.security.egd=file:/dev/./urandom
        restart: on-failure
        logging:
            driver: 'json-file'
            options:
                max-size: '12m'
                max-file: '5'

