version: '2'
    
networks:
    &network http:
        driver: bridge

services:
    http:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/tnginx:2.2.0
        container_name: "tnginx"
        ports:
            - "80:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/conf.d/:/etc/nginx/conf.d/
        networks:
            - *network 
