version: '2'
    
networks:
    &network wlsnet:
        driver: bridge

services:
    http:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/nginx:alpine-1.11.9
        container_name: "nginx"
        ports:
            - "80:80"
        volumes:
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/config/conf.d/:/etc/nginx/conf.d/
        networks:
            - *network 
    &admin adminserver:
        build: &image .
        container_name: wlsadmin
        ports:
            - "8001:8001"
        volumes:
            - './app/:/u01/oracle/app/'
        networks:
            - *network 
        env_file:
            - app.env
    nm1:
        build: *image
        command: createServer.sh
        ports:
            - "7001:7001"
        volumes:
            - './app/:/u01/oracle/app/'
        networks:
            - *network 
        env_file:
            - app.env
        depends_on:
            - *admin
